development:
  adapter: sqlite3
  database: db/sandwich_development.db

test:
  adapter: sqlite3
  database: db/sandwich_test.db

production:
  adapter: sqlite3
  database: ../../shared/db/sandwich_production.db
